version: '3.1'

services: 
  opencv:
    image: tangx/opencv-debian:4.2.0-buster-golang1.14.3
    build:
      context: .
      dockerfile: opencv.Dockerfile
    environment:
      OPENCV_VERSION: 4.2.0
      GOVERSION: 1.14.3


