version: '3.1'

services:
  onbuild-430:
    image: tangx/opencv-alpine:4.3.0-ffmpeg4.0-onbuild
    build: 
      context: 4.3.0-ffmpeg4.0-alpine
      dockerfile: onbuild.Dockerfile
  runtime-430:
    image: tangx/opencv-alpine:4.3.0-ffmpeg4.0-runtime
    build:
      context: 4.3.0-ffmpeg4.0-alpine
      dockerfile: runtime.Dockerfile
    depends_on: 
      - onbuild-430
