version: '3.1'

services:
  ffmpeg-debian:
    image: tangx/ffmpeg-debian:4.1.2-golang1.14.3-buster
    build: 
      context: .
      dockerfile: ffmpeg.Dockerfile
  opencv-debian:
    image: tangx/opencv-debian:4.3.0-ffmpeg4.1.2-golang1.4.3-buster
    build: 
      context: .
      dockerfile: opencv-onbuild.Dockerfile
